

""" 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms.

"""

def fibo_even_sum(n):

    fib = [1, 2]
    sum = 2
    ii = 1

    while (fib[ii] < n ):
        fib.append(fib[ii] + fib[ii-1])
        ii = ii + 1
        if (fib[ii] % 2 == 0):
            sum = sum + fib[ii]

    print(fib)
    print(sum)


fibo_even_sum(20)